alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: lambda-webhook
    receivers:
      - name: lambda-webhook
        webhook_configs:
          - url: "https://ly3dnifgn4dlbkhnan7d452g540dfwqi.lambda-url.ap-south-1.on.aws/"
            send_resolved: true
    templates: []
